# .github/workflows/semgrep.yml
name: Semgrep CE scan
on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: - run: semgrep scan --config auto --config p/security-audit --config p/secrets --config p/nodejs
      
